### PR TITLE
Update WireGuard config's SERVER_PUBLIC_URL to UDP

### LINKED ISSUE #48: Discrepancy in config.ini.example and docs
**Describe the bug**
There's an inconsistency in the documentation and the example configuration file for AIVPN regarding the protocol used in the `SERVER_PUBLIC_URL` for both OpenVPN and WireGuard services. Specifically, the documentation instructs to use TCP for OpenVPN and UDP for WireGuard, while the example config file (`config.ini.example`) has these protocols swapped: it lists OpenVPN with UDP and WireGuard with TCP.

**To Reproduce**

1. Visit the AIVPN [documentation page](https://aivpn.readthedocs.io/en/latest/configuration.html#setting-up-the-openvpn-configuration).
2. Note the instructions for setting up the OpenVPN and WireGuard VPN configurations, which specify using TCP for OpenVPN and UDP for WireGuard.
3. Compare with the [config.ini.example](https://github.com/stratosphereips/AIVPN/blob/main/config/config.ini.example) file. (Line 48 & 54)
4. Observe the discrepancy in the SERVER_PUBLIC_URL protocol specification: UDP is mentioned for OpenVPN and TCP for WireGuard in the example config file, contrary to the documentation.

**Expected behavior**
The documentation and the example configuration file should consistently specify the correct protocols to be used for OpenVPN and WireGuard in the `SERVER_PUBLIC_URL`

**Screenshots**
Screenshot 2024-03-12 at 10 37 24 PM Screenshot 2024-03-12 at 11 06 20 PM

### PR DESCRIPTION
**Pull request by ay-bh**
closes #48 
This updates the SERVER_PUBLIC_URL configuration for the WireGuard VPN setup from TCP to UDP in the `config/config.ini.example`. 

> WireGuard explicitly does not support tunneling over TCP, due to the classically terrible network performance of tunneling TCP-over-TCP.

Source : https://www.wireguard.com/known-limitations/

### CODE REVIEW

**Comment by verovaleros** [comment]
We have this configuration on TCP because, from experience, it worked better, and it had fewer issues during deployment.

Let's have the two options, please. Let's leave the `udp://` by default, and bring back the other option with a comment on 'Switch to this for having TCP instead of UDP'.

Can you do it @ay-bh ?

**Comment by ay-bh** [comment]
@verovaleros Thank you for the feedback. Sure I'll do it.

**Comment by ay-bh** [comment]
@verovaleros Please check now.

**Review by verovaleros — APPROVED** [review]
Fantastic, thanks

**Pull request merged**
